name: jar
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: jar
      run: | 
        git clone --depth=1 --branch=main https://github.com/sheptalo/${{ github.event.repository.name }}
        cd ${{ github.event.repository.name }}
        jar -cfv ${{ github.event.repository.name }}.jar *
    - name: Upload Mod Jar
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ github.event.repository.name }}
        path: ${{ github.event.repository.name }}/*.jar
