name: master

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
- uses: montudor/action-zip@v1
  with:
    args: zip -qq -r dir.zip dir
- uses: actions/upload-artifact@v1
  with:
    name: my-artifact
    path: ${{ github.workspace }}/result.zip
