name: Zip Files
- name: Easy Zip Files
  uses: vimtor/action-zip@v1

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: dist/ manifest.json
          dest: result.zip
